import React, { useState, useEffect } from 'react';
import { collection, query, onSnapshot, addDoc, deleteDoc, doc, Timestamp } from 'firebase/firestore';
import { db, appId } from '../utils/firebase';
import { Trash2 } from 'lucide-react';

const Clients = ({ user }) => {
  const [form, setForm] = useState({ firstName: '', lastName: '', company: '', nit: '', email: '', phone: '', address: '', serviceType: '', billingFrequency: '', startDate: '' });
  const [clients, setClients] = useState([]);
  useEffect(() => { if(!user) return; const unsub = onSnapshot(query(collection(db, 'artifacts', appId, 'public', 'data', 'clients')), (s) => setClients(s.docs.map(d => ({id: d.id, ...d.data()})))); return () => unsub(); }, [user]);
  const add = async (e) => { e.preventDefault(); await addDoc(collection(db, 'artifacts', appId, 'public', 'data', 'clients'), {...form, createdAt: Timestamp.now()}); };
  const del = async (id) => { if(window.confirm('?')) await deleteDoc(doc(db, 'artifacts', appId, 'public', 'data', 'clients', id)); };
  return ( <div className="space-y-8"><div className="bg-white p-8 rounded-3xl shadow-lg"><h3 className="text-xl font-black mb-6 text-[#522b85]">Cliente</h3><form onSubmit={add} className="grid md:grid-cols-2 gap-4"><input value={form.company} onChange={e=>setForm({...form, company: e.target.value})} placeholder="Empresa / Razón Social" className="p-4 border rounded-xl md:col-span-2 font-bold" required/><input value={form.nit} onChange={e=>setForm({...form, nit: e.target.value})} placeholder="NIT" className="p-4 border rounded-xl"/><input value={form.firstName} onChange={e=>setForm({...form, firstName: e.target.value})} placeholder="Contacto" className="p-4 border rounded-xl"/><input value={form.email} onChange={e=>setForm({...form, email: e.target.value})} placeholder="Email" className="p-4 border rounded-xl"/><input value={form.phone} onChange={e=>setForm({...form, phone: e.target.value})} placeholder="Teléfono" className="p-4 border rounded-xl"/><select value={form.serviceType} onChange={e=>setForm({...form, serviceType: e.target.value})} className="p-4 border rounded-xl" required><option value="">Tipo de Servicio...</option><option value="Redes Sociales">Redes Sociales</option><option value="Web">Diseño Web</option><option value="Branding">Branding</option><option value="Consultoría">Consultoría</option></select><select value={form.billingFrequency} onChange={e=>setForm({...form, billingFrequency: e.target.value})} className="p-4 border rounded-xl" required><option value="">Frecuencia...</option><option value="Mensual">Mensual</option><option value="Único">Único</option></select><div><label className="text-[10px] font-bold ml-1">Fecha Inicio</label><input value={form.startDate} type="date" onChange={e=>setForm({...form, startDate: e.target.value})} className="w-full p-3 border rounded-xl"/></div><input value={form.address} onChange={e=>setForm({...form, address: e.target.value})} placeholder="Dirección" className="p-4 border rounded-xl md:col-span-2"/><button className="md:col-span-2 bg-[#522b85] text-white py-4 rounded-xl font-bold">Guardar</button></form></div><div className="grid md:grid-cols-2 gap-4">{clients.map(c => (<div key={c.id} className="bg-white p-6 rounded-2xl border shadow-sm"><div className="flex justify-between"><h4 className="font-black text-lg">{c.company}</h4><span className="text-xs bg-[#f7c303]/20 text-black font-bold px-2 py-1 rounded h-fit">{c.billingFrequency}</span></div><p className="text-sm text-gray-500">{c.nit}</p><p className="text-xs font-bold text-[#522b85]">{c.serviceType}</p><button onClick={()=>del(c.id)} className="text-red-500 float-right"><Trash2/></button></div>))}</div></div> );
};
export default Clients;