import React, { useState, useEffect } from 'react';
import { collection, query, onSnapshot, addDoc, deleteDoc, doc, Timestamp } from 'firebase/firestore';
import { db, appId } from '../utils/firebase';
import { convertToBase64 } from '../utils/helpers';
import { Trash2, Camera } from 'lucide-react';

const Team = ({ user }) => {
  const [members, setMembers] = useState([]);
  const [form, setForm] = useState({ fullName: '', birthDate: '', accountNumber: '', bank: '', role: 'Colaborador', jobTitle: '', photoBase64: '' });
  useEffect(() => { if(!user) return; const q = query(collection(db, 'artifacts', appId, 'public', 'data', 'team')); const unsub = onSnapshot(q, (s) => setMembers(s.docs.map(d => ({id: d.id, ...d.data()})))); return () => unsub(); }, [user]);
  
  const handlePhoto = async (e) => { const f = e.target.files[0]; if(f) setForm({...form, photoBase64: await convertToBase64(f)}); };
  const add = async (e) => { e.preventDefault(); await addDoc(collection(db, 'artifacts', appId, 'public', 'data', 'team'), {...form, createdAt: Timestamp.now()}); };
  const del = async (id) => { if(window.confirm('¿Borrar miembro?')) await deleteDoc(doc(db, 'artifacts', appId, 'public', 'data', 'team', id)); };
  
  return ( <div className="space-y-8"><div className="bg-white p-8 rounded-3xl shadow-lg"><h3 className="text-xl font-black mb-6 text-[#522b85]">Nuevo Miembro</h3><form onSubmit={add} className="space-y-4"><div className="flex items-center gap-4"><div className="w-24 h-24 rounded-full bg-gray-100 overflow-hidden relative group"><img src={form.photoBase64 || "https://placehold.co/100x100/eeeeee/aaaaaa?text=?"} className="w-full h-full object-cover"/><label className="absolute inset-0 flex items-center justify-center bg-black/50 opacity-0 group-hover:opacity-100 cursor-pointer transition-opacity"><Camera className="text-white"/><input type="file" className="hidden" onChange={handlePhoto}/></label></div><div className="flex-1"><input value={form.fullName} onChange={e=>setForm({...form, fullName: e.target.value})} placeholder="Nombre" className="w-full p-4 border rounded-xl mb-4" required/><input value={form.jobTitle} onChange={e=>setForm({...form, jobTitle: e.target.value})} placeholder="Cargo" className="w-full p-4 border rounded-xl" required/></div></div><div className="grid grid-cols-2 gap-4"><input value={form.bank} onChange={e=>setForm({...form, bank: e.target.value})} placeholder="Banco" className="p-4 border rounded-xl"/><input value={form.accountNumber} onChange={e=>setForm({...form, accountNumber: e.target.value})} placeholder="Cuenta" className="p-4 border rounded-xl"/></div><button className="w-full bg-[#522b85] text-white font-bold py-4 rounded-xl">Guardar Miembro</button></form></div><div className="bg-white p-8 rounded-3xl shadow-sm border"><h3 className="text-xl font-black mb-6">Equipo Space</h3><div className="grid md:grid-cols-2 gap-4">{members.map(m => (<div key={m.id} className="bg-gray-50 p-5 rounded-2xl flex items-center gap-4"><div className="w-16 h-16 rounded-full overflow-hidden"><img src={m.photoBase64 || "https://placehold.co/100x100/eeeeee/aaaaaa?text=?"} className="w-full h-full object-cover"/></div><div><p className="font-bold">{m.fullName}</p><p className="text-[#522b85] font-bold text-xs">{m.jobTitle}</p><p className="text-xs">{m.bank} - {m.accountNumber}</p></div><button onClick={()=>del(m.id)} className="text-red-500 ml-auto"><Trash2/></button></div>))}</div></div></div> );
};
export default Team;